language: python

python:
    - 3.6
    - 3.7

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes --all
    - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
    - source activate condaenv

install:
    - conda install -y -c defaults -c gimli -c conda-forge pybert
    - conda update -f -c defaults -c gimli -c conda-forge pybert

script:
    - python -c "import pygimli; pygimli.test(onlydoctests=True, show=False, abort=True)"
    - python -c "import pybert"
    - which bert
    - dcinv -h
    - gimlipath=`python -c "import pygimli; print(pygimli.__path__[0])"`
    - ldd $gimlipath/core/_pygimli_.so
    - echo "DONE."
