language: python

env:
  - PY=3.6
  - PY=3.7
 
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -c gimli -c conda-forge -q -n test-environment python=$PY pybert
  - source activate test-environment

script:
  - python -c "import pygimli; pygimli.test(onlydoctests=True, show=False, abort=True)"
  - python -c "import pybert"
  - which bert
  - dcinv -h
  - gimlipath=`python -c "import pygimli; print(pygimli.__path__[0])"`
  - ldd $gimlipath/core/_pygimli_.so
  - echo "DONE."
