package:
    name: pygimli
    version: {{ GIT_DESCRIBE_TAG }}

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    rpaths:
        - lib/
        - lib64/

source:
    git_url: https://github.com/gimli-org/gimli.git
    git_tag: dev # build from dev branch

requirements:
    build:
        - boost ==1.64
        - gcc >=4.7
        - cmake >=2.8.10
        - python
        - numpy x.x
        - openblas
        - wget # [not linux]

    run:
        - boost ==1.64
        - python
        - numpy x.x
        - matplotlib >=2.0
        - openblas
        - scipy # for workshop only
        - pytest

test:
    imports:
        - pygimli
    commands:
        - pytripatch -h # Python app
        - python -c "import pygimli; pygimli.test(onlydoctests=True, abort=True)"

about:
    home: http://www.pygimli.org
    summary: Geophysical Inversion and Modelling Library
    license: Apache 2.0
