package:
    name: pygimli
    version: 1.1rc

build:
    number: 5
    rpaths:
        - lib/
        - lib64/

source:
    #git_url: https://github.com/gimli-org/gimli.git
    #git_tag: dev # build from dev branch
    #path: /home/fwagner/src/gimli/gimli
    path: /home/wagner/git/gimli/trunk

requirements:
    build:
        - gcc >=4.7
        - cmake >=2.8.10
        - python
        - boost ==1.64
        - numpy >=1.13
        - openblas
        - wget # [not linux]

    run:
        - boost ==1.64
        - numpy >=1.13
        - matplotlib >=2.0
        - openblas
        - scipy # for workshop only
        - pytest

test:
    imports:
        - pygimli
    commands:
        - pytripatch -h # Python app
        - python -c "import pygimli; pygimli.test(onlydoctests=True, abort=True)"

about:
    home: http://www.pygimli.org
    summary: Geophysical Inversion and Modelling Library
    license: Apache 2.0
