package:
    name: pygimli
    version: 1.0

build:
    number: 1
    rpaths:
        - lib/
        - lib64/

source:
    #git_url: https://github.com/gimli-org/gimli.git
    #git_tag: dev # build from dev branch
    #path: /home/fwagner/src/gimli/gimli
    #path: /home/wagner/git/gimli/trunk
    path: /Users/flocke/gimli

requirements:
    build:
        - gcc >=4.7
        - libgcc
        - cmake >=2.8.10
        - python
        - boost ==1.63
        - numpy x.x
        - openblas
        - wget
        #- suitesparse

    run:
        - libgcc
        - python
        - boost ==1.63
        - numpy x.x # RVector.array() bug mit 1.12
        - pyqt ==4.11.4 # current mpl/qt bug with qt 5.6
        - matplotlib
        - openblas
        - scipy # for workshop only
        - pytest
        #- suitesparse

test:
    imports:
        - pygimli
    commands:
        # - harmfit -h # C++ app
        - pytripatch -h # Python app
        - python -c "import pygimli; pygimli.test(onlydoctests=True)"

about:
    home: http://www.pygimli.org
    summary: Geophysical Inversion and Modelling Library
    license: Apache 2.0
