MACOSX_DEPLOYMENT_TARGET:
  - "13.0"
MACOSX_SDK_VERSION:
  - "13.0"

boost:
  - 1.85

python:
  - 3.10
  - 3.11
  - 3.12

numpy:
  - 1.26
  - 2.1
  - 2.2

pin_run_as_build:
  boost: x.x
  python: x.x
  numpy: x.x
