package:
    name: pybert
    version: 2.2.4

build:
    number: 9
    rpaths:
        - lib/
        - lib64/

source:
    #git_url: https://github.com/gimli-org/gimli.git
    #git_tag: dev # build from dev branch
    path: /home/wagner/git/bert

requirements:
    build:
        - gcc >=4.7
        - boost ==1.64
        - numpy x.x
        - pygimli
        - python

    run:
        - boost ==1.64
        - pygimli
        - numpy x.x
        - tetgen
        - python

test:
    imports:
      - pybert
    commands:
      - dcinv -h

about:
    home: http://www.resistivity.net
    summary: Boundless Electrical Resistivity Tomography
