package:
    name: pybert
    version: 2.2.0

build:
    number: 5
    rpaths:
        - lib/
        - lib64/

source:
    #git_url: https://github.com/gimli-org/gimli.git
    #git_tag: dev # build from dev branch
    path: /home/wagner/git/bert/trunk

requirements:
    build:
        - gcc >=4.7
        - libgcc
        - pygimli
        - cmake >=2.8.10
        - python
        - boost >=1.64
        - numpy x.x
        - openblas

    run:
        - pygimli
        - python
        - tetgen

test:
    imports:
      - pybert
    commands:
      - dcinv -h

about:
    home: http://www.resistivity.net
    summary: Boundless Electrical Resistivity Tomography
