package:
    name: pybert
    version: 2.2.6rc

build:
    number: 12
    rpaths:
        - lib/
        - lib64/

source:
    #git_url: https://gitlab.com/resistivity-net/bert
    #git_tag: dev # build from dev branch
    path: /home/wagner/git/bert/trunk

requirements:
    build:
        - gcc >=4.7
        - boost ==1.65.1
        - numpy x.x
        - pygimli
        - python x.x

    run:
        - boost ==1.65.1
        - pygimli
        - numpy x.x
        - tetgen
        - python x.x

test:
    imports:
      - pybert
    commands:
      - dcinv -h

about:
    home: http://www.resistivity.net
    summary: Boundless Electrical Resistivity Tomography
