package:
    name: pybert
    version: 2.2.6rc

build:
    number: 13
    rpaths:
        - lib/
        - lib64/

source:
    #git_url: https://gitlab.com/resistivity-net/bert
    #git_tag: dev # build from dev branch
    path: /home/wagner/git/bert/trunk

requirements:
    build:
        # Make sure libgcc 5.* is not used at build time
        - libgcc 4.8.*  # [linux]
        - gcc 4.8.*  # [linux]
        - boost 1.66.0
        - numpy x.x
        - pygimli
        - python x.x

    run:
        - boost 1.66.0
        - pygimli
        - numpy x.x
        - tetgen
        - python x.x

test:
    imports:
      - pybert
    commands:
      - dcinv -h

about:
    home: http://www.resistivity.net
    summary: Boundless Electrical Resistivity Tomography
